django_blog/api/urls.py
from django.urls import path, re_path , include
from rest_framework import routers
from . import views

app_name='api'

router = routers.DefaultRouter()
router.register('posts' , views.PostView)
router.register('users' , views.UserView)

urlpatterns = [
    path("v1/" , include(router.urls)),
    path("v1/changepassword" , views.ChangePasswordView.as_view()),
    path("v1/like_post/<int:post_id>" , views.like_post_api)
]

django_blog/blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    #path('', views.home , name='blog-home'),
    path('', views.PostListView.as_view(), name='blog-home'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
    path('post/new/', views.PostCreateView.as_view(), name='post-create'),
    path('user/<str:username>', views.UserPostListView.as_view(), name='user-posts'),
    path('like_post/' , views.like_post, name="like_post"),
    path('like_dislike_comments/' , views.like_dislike_comments , name="like_dislike_comments"),
    path('about/', views.about , name='blog-about'),
]

django_blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from users import views as user_views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('blog/' , include('blog.urls')),
    path('' , include('blog.urls')),
    #path('register/' , user_views.register , name='register'),
    path('register/', user_views.Register.as_view(), name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user_views.activate, name='activate'),
    path('profile/' , user_views.profile , name='profile'),
    path('login/' , auth_views.LoginView.as_view(template_name='users/login.html') , name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    
    path('ckdeditor/', include('ckeditor_uploader.urls')),
    
    path('password_change/' , user_views.PasswordChange.as_view(
        template_name='users/password_change_form.html') , name='passwordchange'),
    path('password_change/done/' , auth_views.PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html') , name='passwordchangedone'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html' , email_template_name='users/password_reset_email.html'), name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),

    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'), name='password_reset_complete'),

    #for api
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

django_blog/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image as PilImage
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    #content = models.TextField()
    #content = RichTextField()
    content = RichTextUploadingField()
    #image = models.ImageField(null=True , blank=True , upload_to='post_images') #add ckeditor so we need this anymore
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User ,related_name='author', on_delete=models.CASCADE)
    user_like=models.ManyToManyField(User,related_name="likes",blank=True)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post-detail", kwargs={"pk": self.pk})

    #add ckeditor so we need this anymore
    """ 
    def save(self, *args, **kwargs):
        super().save(*args , **kwargs)

        if self.image : #beecause image maybe null
            img = PilImage.open(self.image.path)
        
            if img.height > 500 or img.width > 700 :
                output_size = (700,500)
                img.thumbnail(output_size)
                img.save(self.image.path)
    """
    
class Comment(models.Model):
    writer = models.ForeignKey(User , on_delete=models.CASCADE , related_name='commentor')
    post = models.ForeignKey(Post, on_delete=models.CASCADE , related_name='comments')
    body = models.TextField(max_length=200, help_text="Add your comment")
    created = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE , null=True, blank=True, related_name='replies')
    comment_like=models.ManyToManyField(User,related_name="user_comment_likes",blank=True)
    comment_dislike=models.ManyToManyField(User,related_name="user_comment_dislikes",blank=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {}'.format(self.writer.username)

django_blog/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
import os

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE , related_name="profile")
    image = models.ImageField(null=True , blank = True ,default='default.jpg', upload_to='progile_pics')
    bio = models.TextField(null=True , blank = True , max_length=500)
    location = models.CharField(null=True , blank = True , max_length=100)
    birthday = models.DateField(null=True , blank = True , auto_now=False, auto_now_add=False)

    def __str__(self):
        return f'{self.user.username} Profile'
    
    def save(self, *args, **kwargs):
        
        super().save(*args , **kwargs)

        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300 :
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

django_blog/blog/forms.py
from django import forms
from .models import Post , Comment 

class PostView(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content']

        #widgets = {'image': forms.FileInput(attrs={'id': 'postimageform'}) }
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body' ,]

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['body'].widget = forms.Textarea(attrs={'rows': 3, })
        #pass

django_blog/blog/views.py
from django.shortcuts import render , get_object_or_404
from django.http import HttpResponse , JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin , UserPassesTestMixin
from django.views.generic import ListView , DetailView ,CreateView , UpdateView , DeleteView
from django.contrib.auth.models import User
from .models import Post , Comment
from users.models import Profile
from django.db.models import Q
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.template.loader import render_to_string


from .forms import PostView , CommentForm

# Create your views here.

def home(request):
    posts = Post.objects.all()
    context = {
        'posts' : posts
    }
    return render(request , 'blog/home.html' , context)

class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 6
    
    def get(self, request, *args, **kwargs):
        #for search
        if request.GET.get("q"):
            search_word =  request.GET.get("q")
            self.queryset = Post.objects.filter(Q(title__icontains = search_word) |
                        Q(content__icontains = search_word) ).distinct()

        return super(PostListView, self).get(request, *args, **kwargs)

def like_post(request):
    user = request.user
    if request.method=='POST' and request.is_ajax() :
        post = Post.objects.get(id = request.POST.get('pk'))
        if(post.author == user):
            return JsonResponse({'like':'False'})
        if (not post.user_like.filter(id=user.id).exists()) : #if not in likers add it
            post.user_like.add(user)
            return JsonResponse({'liked':'True'})
        elif(post.user_like.filter(id=user.id).exists()) : #if in likers remove it
            post.user_like.remove(user)
            return JsonResponse({'disliked':'True'})

class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 6


    def get_context_data(self, **kwargs):
        context = super(UserPostListView, self).get_context_data(**kwargs)

        user = get_object_or_404(User , username=self.kwargs.get('username'))
        profile = Profile.objects.filter(user = user)[0]
        
        context['profile'] = profile
        return context
    
    def get_queryset(self):
        user = get_object_or_404(User , username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')    

class PostDetailView(DetailView):
    model = Post
    #for default templates => <app>/<model>_<ViewType>
    #for default context name => object
    comment_form_class = CommentForm

    '''def get(self, request , *args, **kwargs):
        return super(PostDetailView, self).get(request, *args, **kwargs)'''

    def post(self, request, *args, **kwargs):

        #this is for comment on post
        if 'submit_comment' in request.POST:
            comment_form = self.comment_form_class(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.writer = self.request.user
                comment.post = self.get_object()
                comment.save()
        
        #this is for reply a comment
        if 'submit_reply' in request.POST:
            parent = Comment.objects.get(pk=self.request.POST.get('parent_id'))
            comment_form = self.comment_form_class(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.writer = self.request.user
                comment.post = self.get_object()
                comment.parent = parent #!
                comment.save()
        
        return super(PostDetailView, self).get(request, *args, **kwargs)

    '''def form_valid(self, form):
        print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
        comment_form = form.save(commit=False)
        comment_form.writer = self.request.user
        comment_form.post = self.self.get_object()
        comment_form.save()
        return super(PostDetailView, self).form_valid(form)'''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = self.comment_form_class
        return context

#for like or dislike a commnet
def like_dislike_comments(request):
    if request.user.is_authenticated:
        user = request.user
        if request.method=='POST':
            comment = Comment.objects.get(id = request.POST.get('pk'))
            if request.POST.get('like'): #delete from dislike and add to likes
                if comment.comment_dislike.filter(id=user.id).exists():
                    comment.comment_dislike.remove(user)
                if not comment.comment_like.filter(id=user.id):
                    comment.comment_like.add(user)
                    return JsonResponse({'status':'liked' , 'liked':comment.comment_like.count() , 'disliked':comment.comment_dislike.count()})
                else: #if user liked Alredy and requset for like again so unlike it
                    comment.comment_like.remove(user)
                    return JsonResponse({'status':'unliked' , 'liked':comment.comment_like.count() , 'disliked':comment.comment_dislike.count()})

            elif request.POST.get('dislike'): #delete from like and add to dislikes
                if comment.comment_like.filter(id=user.id).exists():
                    comment.comment_like.remove(user)
                if not comment.comment_dislike.filter(id=user.id):
                    comment.comment_dislike.add(user)
                    return JsonResponse({'status':'disliked' , 'liked':comment.comment_like.count() , 'disliked':comment.comment_dislike.count()})
                else: #if user disliked Alredy and requset for dislike again so undislike it.
                    comment.comment_dislike.remove(user)
                    return JsonResponse({'status':'undisliked' , 'liked':comment.comment_like.count() , 'disliked':comment.comment_dislike.count()})
                
            #return like number and dislike number with JSON    
            return JsonResponse({'status':'error' , 'liked':comment.comment_like.count() , 'disliked':comment.comment_dislike.count()})
    else: #if user not authenticated
        return JsonResponse({'status':'error' , 'liked':'not login' , 'disliked':'not login'})

class PostCreateView(LoginRequiredMixin , CreateView):
    model = Post
    #fields = ['title','content','image']
    #default template is <model>_form because is shared with updateView
    form_class = PostView
    #for set author field with current login user
    def form_valid(self , form):
        create_post_email(self.request.user , form.instance.title)
        form.instance.author = self.request.user
        return super().form_valid(form)

#send a email when user create a new post
def create_post_email(user , title):
    if user.email :
        subject = 'You Create a POST !'
        from_email ='mydjangoapp@gmail.com'
        to = user.email
        context = {'user': user.email,'post_name': title}
        html_content = render_to_string('blog/create_post_email.html', context)
        plain_message = strip_tags(html_content)
        try:
            send_mail(subject , plain_message , from_email , [to] , fail_silently=False , html_message=html_content)
        except Exception as e:
            print("\n****Error in sending email for create a post****\n")
            print(e)
            print("\n****Error in sending email for create a post****\n")

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin , UpdateView):
    model = Post
    fields = ['title','content']
    #default template is <model>_form because is shared with createView
    
    #for set author field with current login user
    def form_valid(self , form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    #for check current user == auther of this post
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author :
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin , DeleteView):
    model = Post
    success_url = '/'
    
    #for check current user == auther of this post
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

def about(request):
   return render(request , 'blog/about.html' , {'title':'about'}) 

django_blog/blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
    <article class="media content-section">
        <div class="container">
            <div class="row about-title justify-content-center">
                <h1>about us!!</h1>
            </div>
            <div class="row">
                <p>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore
                    magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl
                    ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie
                    consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit
                    praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore
                    magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl
                    ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie
                    consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit
                    praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore
                    magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl
                    ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie
                    consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit
                    praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                </p>
            </div>
        </div>
    </article>
{% endblock content%}

django_blog/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    </head>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    <script src="{% static 'blog/js/jquery-3.3.1.min.js' %}"></script>
    {% if title %}
        <title>Django Blog - {{ title }}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link href="{% static 'blog/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css"> -->
    <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->
    <script src="https://code.iconify.design/1/1.0.3/iconify.min.js"></script>
    <link href="css/style.css" rel="stylesheet">
</head>

<body>

<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Django Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
                    <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'profile' %}"><img class="mr-2 rounded-circle" src='{{g_profile.image.url}}' style="background-color: red; width:30px; height:30px;">MyProfile</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                        {% if user.is_staff %}
                            <a class="nav-item nav-link" href="{% url 'admin:index' %}">AdminPage</a>
                        {% endif %}
                        {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
                <h3>Quick Access Toolbar</h3>
                <p class='text-muted'>
                    <ul class="list-group">
                        <li class="list-group-item mb-3 list-group-item-light">
                            <form class="form-inline" method="GET" action="{%url 'blog-home' %}">
                                <input class="form-control w-100" type="search" placeholder="Search" name="q">
                                <button class="btn btn-outline-success w-100 mx-2 my-2" type="submit">Search</button>
                            </form>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="list-group-item mb-3 list-group-item-light"><a class="" href="{% url 'post-create' %}">Create a Post</a></li>
                            <li class="list-group-item mb-3 list-group-item-light"><a class="" href="{% url 'profile' %}">Go to my Profile</a></li>
                        {% else %} 
                            <li class="list-group-item mb-3 list-group-item-light"><a class="" href="{% url 'register' %}">Join Us</a></li>
                        {% endif %}
                    </ul>
                </p>
            </div>
            <div class="content-section mt-5">
                <h3 class="mb-3">Last Posts</h3>
                <ul class="list-group">
                    {% for post in g_last_posts %}
                    <li class="list-group-item mb-3 list-group-item-light"><a class="text-muted" href="{% url 'post-detail' post.id %}">{{post.title}}</a></li> 
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</main>

<!-- Footer -->
<footer class="page-footer font-small">

    <div class="container">

        <!-- Links row-->
        <div class="row text-center d-flex justify-content-center pt-4 mb-20">

            <!-- Links column -->
            <div class="col-md-2 mb-3">
                <h6 class="text-uppercase font-weight-bold">
                    <a href="#!" class="footer-links">About us</a>
                </h6>
            </div>
            <!-- Links column -->

            <!-- Links column -->
            <div class="col-md-2 mb-3">
                <h6 class="text-uppercase font-weight-bold">
                    <a href="#!" class="footer-links">Products</a>
                </h6>
            </div>
            <!-- Links column -->

            <!-- Links column -->
            <div class="col-md-2 mb-3">
                <h6 class="text-uppercase font-weight-bold">
                    <a href="#!" class="footer-links">Awards</a>
                </h6>
            </div>
            <!-- Links column -->

            <!-- Links column -->
            <div class="col-md-2 mb-3">
                <h6 class="text-uppercase font-weight-bold">
                    <a href="#!" class="footer-links">Help</a>
                </h6>
            </div>
            <!-- Links column -->

            <!-- Links column -->
            <div class="col-md-2 mb-3">
                <h6 class="text-uppercase font-weight-bold">
                    <a href="#!" class="footer-links">Contact</a>
                </h6>
            </div>
            <!-- Links column -->

        </div>
        <!-- Links row-->
        <hr class="rgba-white-light" style="margin: 0 15%;">



        
        <!-- Text row-->
        <div class="row d-flex text-center justify-content-center mb-md-0 mb-4">

            <!-- Text column -->
            <div class="col-md-8 col-12 mt-2">
                <p style="line-height: 1.7rem">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
                aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat
                </p>
            </div>
            <!-- Text column -->

        </div>
        <!-- Text row-->
        <hr class="clearfix d-md-none rgba-white-light" style="margin: 10% 15% 5%;">




        <!-- Icons row-->
        <div class="row pb-3">

            <!-- Icons column -->
            <div class="col-md-12 text-center mb-2 mt-2">

                <ul class="list-inline social-buttons">
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="iconify" data-icon="el:twitter" style="color: #e2e2e2;"></span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="iconify" data-icon="dashicons:facebook-alt" style="color: #e2e2e2;"></span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="iconify" data-icon="ic:round-mail" style="color: #e2e2e2;"></span>
                        </a>
                    </li>
                </ul>

            </div>
            <!-- Icons column -->

        </div>
        <!-- Icons row-->

    </div>

    <!-- Copyright -->
    <div class="footer-copyright text-center py-2">© 2020 Copyright:
        <a  class="footer-links" href="https://mdbootstrap.com/education/bootstrap/"> Gitlab.com/jazi</a>
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->
    
</body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'blog/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'blog/js/popper.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
</html>

django_blog/blog/templates/blog/create_post_email.html
<h1 style="color:crimson;">Hi {{user}}</h1>
<h3>You just create post with name &nbsp;:&nbsp; {{post_name}}</h3>
<p style="margin-top: 50px;">tanks</p>

django_blog/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Post</legend>
            <h2>Are you sure want to delete the post "{{ object.title }}"</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes , Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

django_blog/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<script src="{% static 'blog/js/like.js' %}"></script>
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{% url 'user-posts' object.author.username %}">{{ object.author }}</a>
            <small class="text-muted">{{ object.date_posted | date:"l , d F Y" }}</small>
            <small class="time-post">{{ object.date_posted | date:"G:i" }}</small>
        </div>
        <h2 class="article-title">{{ object.title }}
            <!-- edit delete -->
            {% if object.author == user %}
                <a class="btn btn-sm mt-10 mb-1 float-right" href="{% url 'post-update' object.id %}"><span class="iconify"
                    data-icon="bx:bx-edit" data-inline="false" data-width="20px"></span></a>
                <a class="btn btn-sm mt-1 mb-1 float-right" href="{% url 'post-delete' object.id %}"><span class="iconify"
                    data-icon="ant-design:delete-fill" style="color: red;" data-width="20px"></span></a>
            {% endif %}
            
            <!-- like -->
            {% if user.is_authenticated and user != post.author %}
            <a class="likebtn btn float-right" pk="{{post.id}}" style="background-color: transparent;">
                <span class="iconify" data-icon="ion:heart-sharp" data-inline="false" {% if user in post.user_like.all %} style="color: red ;" {% else %} style="color: #cebdbd;" {% endif %} data-width="32" data-height="32"></span>
            </a>
            {% endif %}
        </h2>
        <p class="article-content">{{ object.content | safe }}</p>
        
        <!--
        {% if post.image %}
        <div class="text-center mb-1">
            <img src="{{post.image.url}}" style="width:auto;height:auto;max-width:100%;max-height:100%;">
        </div>
        {% endif %}
        -->
        
    </div>
</article>

{% include 'blog/comments.html' %}

{% endblock content%}

django_blog/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Blog Post</legend>
            {{form.media}}
            {{form|crispy}}
        </fieldset>
        {% if form.instance.image %}
        <img class="mb-3" id="currentimage" src="{% if form.instance.image.url %}{{form.instance.image.url}}{%else%}#{%endif%} " style="width:auto;height:auto;max-width:100%;max-height:100%;">
        {% endif %}
        <fieldset class="form-group text-right">
            <button class="btn btn-info btn-lg" type="submit">Post</button>
        </fieldset>
    </form>
</div>
<script>
    /*
    $("#id_image").change(function(){
        $("#currentimage").attr("src" , $("#id_image").path()); //but not work for some security feature browser
    });
    */
</script>
{% endblock content %}